
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("2.1.10.21")]
 [assembly: AssemblyFileVersion("2.1.10.21")]
 [assembly: KSPAssembly("ClickThroughBlocker", 2, 1, 0)]